from fastapi import APIRouter
from app.api.v1.endpoints import ingest, analytics, teacher, subjects, exams, auth, institutions, users, classes, notifications, contact, syllabus, ai_exams, admin_analytics, settings, announcements, audit_logs, ai_usage, server_admin, practice, leaderboard, legal_strategy, tokens

api_router = APIRouter()

api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(ingest.router, prefix="/ingest", tags=["ingest"])
api_router.include_router(analytics.router, prefix="/analytics", tags=["analytics"])
api_router.include_router(teacher.router, prefix="/teacher", tags=["teacher"])
api_router.include_router(subjects.router, prefix="/subjects", tags=["subjects"])
api_router.include_router(exams.router, prefix="/exams", tags=["exams"])
api_router.include_router(institutions.router, prefix="/institutions", tags=["institutions"])
api_router.include_router(users.router, prefix="/users", tags=["users"])
api_router.include_router(classes.router, prefix="/classes", tags=["classes"])
api_router.include_router(notifications.router, prefix="/notifications", tags=["notifications"])
api_router.include_router(contact.router, prefix="/contact", tags=["contact"])
api_router.include_router(syllabus.router, prefix="/syllabus", tags=["syllabus"])
api_router.include_router(ai_exams.router, prefix="/ai-exams", tags=["ai-exams"])
api_router.include_router(admin_analytics.router, prefix="/admin-analytics", tags=["admin-analytics"])
api_router.include_router(settings.router, prefix="/settings", tags=["settings"])
api_router.include_router(announcements.router, prefix="/announcements", tags=["announcements"])
api_router.include_router(audit_logs.router, prefix="/audit-logs", tags=["audit-logs"])
api_router.include_router(ai_usage.router, prefix="/ai-usage", tags=["ai-usage"])
api_router.include_router(server_admin.router, prefix="/server", tags=["server-admin"])
api_router.include_router(practice.router, prefix="/practice", tags=["practice"])
api_router.include_router(leaderboard.router, prefix="/leaderboard", tags=["leaderboard"])
api_router.include_router(legal_strategy.router, prefix="/legal-strategy", tags=["legal-strategy"])
api_router.include_router(tokens.router, prefix="/tokens", tags=["tokens"])
